<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Members - {{ $institution->name }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #7c3aed;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #1a202c;
            margin: 0;
        }
        .header p {
            color: #718096;
            margin: 5px 0 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #7c3aed;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 12px;
            text-transform: uppercase;
        }
        td {
            padding: 8px 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 12px;
        }
        tr:hover {
            background-color: #f7fafc;
        }
        .footer {
            text-align: center;
            color: #718096;
            font-size: 11px;
            border-top: 1px solid #e2e8f0;
            padding-top: 15px;
            margin-top: 30px;
        }
        .badge {
            display: inline-block;
            padding: 2px 10px;
            border-radius: 20px;
            font-size: 10px;
            font-weight: 600;
        }
        .badge-approved { background: #c6f6d5; color: #22543d; }
        .badge-pending { background: #fefcbf; color: #744210; }
        .role-librarian { background: #bee3f8; color: #2a4365; }
        .role-instructor { background: #c6f6d5; color: #22543d; }
        .role-admin { background: #e9d8fd; color: #44337a; }
        .role-user { background: #e2e8f0; color: #2d3748; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $institution->name }}</h1>
        <p>Members Directory - Generated on {{ $date }}</p>
        <p>Total Members: {{ $total }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Joined</th>
            </tr>
        </thead>
        <tbody>
            @foreach($members as $index => $member)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $member->full_name }}</td>
                <td>{{ $member->email }}</td>
                <td>
                    @php
                        $role = $member->getRoleNames()->first() ?? 'user';
                        $roleClass = match($role) {
                            'librarian' => 'role-librarian',
                            'instructor' => 'role-instructor',
                            'institution_admin' => 'role-admin',
                            default => 'role-user'
                        };
                    @endphp
                    <span class="badge {{ $roleClass }}">{{ ucfirst($role) }}</span>
                </td>
                <td>
                    @if($member->email_verified_at)
                        <span class="badge badge-approved">✅ Active</span>
                    @else
                        <span class="badge badge-pending">⏳ Pending</span>
                    @endif
                </td>
                <td>{{ $member->created_at->format('M d, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by JLIBRARY System v1.0</p>
        <p>This document is confidential and for internal use only.</p>
    </div>
</body>
</html>